# Generated by Django 5.0 on 2025-11-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('orange', 'Orange')], default='blue', max_length=20),
        ),
    ]
