# Generated by Django 5.1.13 on 2025-11-07 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task_assigned_by_task_is_deletable_group_task_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group this task was assigned to (leave empty if assigning to a user)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.group'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User this task is assigned to (leave empty if assigning to a group)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
