# Generated by Django 5.1.13 on 2025-11-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_task_group_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('work', 'Work'), ('personal', 'Personal'), ('school', 'School'), ('health', 'Health'), ('social', 'Social'), ('other', 'Other')], default='', max_length=50),
        ),
    ]
